// src/types/errors.ts

/**
 * 错误码定义
 */
export const ErrorCodes = {
  // 工作区错误
  WORKSPACE_EXISTS: "WORKSPACE_EXISTS",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  WORKSPACE_ACTIVE: "WORKSPACE_ACTIVE",
  WORKSPACE_ARCHIVED: "WORKSPACE_ARCHIVED",
  WORKSPACE_ERROR: "WORKSPACE_ERROR",
  INVALID_NAME: "INVALID_NAME",
  INVALID_PATH: "INVALID_PATH",
  INIT_FAILED: "INIT_FAILED",

  // 节点错误
  NODE_NOT_FOUND: "NODE_NOT_FOUND",
  PARENT_NOT_FOUND: "PARENT_NOT_FOUND",
  INVALID_TITLE: "INVALID_TITLE",
  INVALID_CONTENT: "INVALID_CONTENT",
  INVALID_ACCEPTANCE_CRITERIA: "INVALID_ACCEPTANCE_CRITERIA",
  CANNOT_DELETE_ROOT: "CANNOT_DELETE_ROOT",

  // 状态转换错误
  INVALID_TRANSITION: "INVALID_TRANSITION",
  MISSING_NODE_HASH: "MISSING_NODE_HASH",
  CONCLUSION_REQUIRED: "CONCLUSION_REQUIRED",
  CONCLUSION_TOO_LONG: "CONCLUSION_TOO_LONG",
  CONCLUSION_STALE: "CONCLUSION_STALE",
  CONCLUSIONS_HASH_REQUIRED: "CONCLUSIONS_HASH_REQUIRED",
  CONCLUSIONS_HASH_MISMATCH: "CONCLUSIONS_HASH_MISMATCH",
  INFO_COLLECTION_REQUIRED: "INFO_COLLECTION_REQUIRED",
  INVALID_CONFIRMATION_TOKEN: "INVALID_CONFIRMATION_TOKEN",
  CONFIRMATION_MISMATCH: "CONFIRMATION_MISMATCH",

  // 引用错误
  REFERENCE_NOT_FOUND: "REFERENCE_NOT_FOUND",
  REFERENCE_EXISTS: "REFERENCE_EXISTS",

  // 备忘错误
  MEMO_NOT_FOUND: "MEMO_NOT_FOUND",

  // 日志错误
  LOG_APPEND_FAILED: "LOG_APPEND_FAILED",

  // 节点类型错误
  INVALID_NODE_TYPE: "INVALID_NODE_TYPE",
  INVALID_NODE_ROLE: "INVALID_NODE_ROLE",
  EXECUTION_CANNOT_HAVE_CHILDREN: "EXECUTION_CANNOT_HAVE_CHILDREN",
  INVALID_PARENT_STATUS: "INVALID_PARENT_STATUS",
  INCOMPLETE_CHILDREN: "INCOMPLETE_CHILDREN",
  CONCURRENT_EXECUTION: "CONCURRENT_EXECUTION",
  RULES_HASH_MISMATCH: "RULES_HASH_MISMATCH",
  INVALID_PARAMS: "INVALID_PARAMS",
  UNKNOWN_PARAMS: "UNKNOWN_PARAMS",
  CONTENT_CHANGED: "CONTENT_CHANGED",
  NO_MATCH: "NO_MATCH",
  MULTI_MATCH: "MULTI_MATCH",

  // 校验错误
  GRAPH_CORRUPTED: "GRAPH_CORRUPTED",
  NODE_DIR_MISSING: "NODE_DIR_MISSING",
  NODE_INFO_MISSING: "NODE_INFO_MISSING",

  // 派发错误
  GIT_NOT_FOUND: "GIT_NOT_FOUND",
  DISPATCH_CONFLICT: "DISPATCH_CONFLICT",
  DISPATCH_NOT_ENABLED: "DISPATCH_NOT_ENABLED",
  DISPATCH_REQUIRED: "DISPATCH_REQUIRED",
  DISPATCH_IN_PROGRESS: "DISPATCH_IN_PROGRESS",
  INVALID_NODE_STATUS: "INVALID_NODE_STATUS",
  INVALID_TEST_NODE: "INVALID_TEST_NODE",
  EXEC_NODE_NOT_FOUND: "EXEC_NODE_NOT_FOUND",
  DISPATCH_ALREADY_ENABLED: "DISPATCH_ALREADY_ENABLED",
  DISPATCH_MODE_CONFLICT: "DISPATCH_MODE_CONFLICT",
  GIT_ENVIRONMENT_LOST: "GIT_ENVIRONMENT_LOST",
  NODE_NOT_READY: "NODE_NOT_READY",
  DISPATCH_SKIP: "DISPATCH_SKIP",
  INVALID_DISPATCH_PARENT: "INVALID_DISPATCH_PARENT",
  INVALID_DISPATCH_STATUS: "INVALID_DISPATCH_STATUS",
  DISPATCH_CHILDREN_EXIST: "DISPATCH_CHILDREN_EXIST",

  // 配置错误
  INVALID_CONFIG: "INVALID_CONFIG",

  // 版本错误
  VERSION_TOO_HIGH: "VERSION_TOO_HIGH",
  VERSION_READONLY: "VERSION_READONLY",

  // 安全错误
  UNBOUND_WRITE_DENIED: "UNBOUND_WRITE_DENIED",
} as const;

/**
 * 错误码类型
 */
export type ErrorCode = keyof typeof ErrorCodes;

/**
 * 自定义错误类
 */
export class TanmiError extends Error {
  constructor(
    public code: ErrorCode,
    message: string
  ) {
    super(message);
    this.name = "TanmiError";
  }
}

/**
 * 错误消息映射
 */
export const ErrorMessages: Record<ErrorCode, string> = {
  WORKSPACE_EXISTS: "工作区已存在",
  WORKSPACE_NOT_FOUND: "工作区不存在",
  WORKSPACE_ACTIVE: "工作区处于活动状态，无法删除（使用 force 强制删除）",
  WORKSPACE_ARCHIVED: "工作区状态不符合操作要求",
  WORKSPACE_ERROR: "工作区处于错误状态，需要修复",
  INVALID_NAME: "名称不合法，不能包含特殊字符: / \\ : * ? \" < > |",
  INVALID_PATH: "路径不合法或不存在",
  INIT_FAILED: "工作区初始化失败",
  NODE_NOT_FOUND: "节点不存在",
  PARENT_NOT_FOUND: "父节点不存在",
  INVALID_TITLE: "标题不合法，不能包含特殊字符: / \\ : * ? \" < > |",
  INVALID_CONTENT: "内容格式不合法，包含会破坏解析的字符",
  INVALID_ACCEPTANCE_CRITERIA: "验收标准格式错误，应为对象数组而非字符串数组",
  CANNOT_DELETE_ROOT: "无法删除根节点",
  INVALID_TRANSITION: "非法状态转换",
  MISSING_NODE_HASH: "必须提供 nodeHash 参数，请先调用 node_get 获取节点的 nodeHash",
  CONCLUSION_REQUIRED: "complete/fail 动作必须提供 conclusion",
  CONCLUSION_TOO_LONG: "结论过长，请创建 memo 记录详情后提交精简结论",
  CONCLUSION_STALE: "结论已过期，请先更新结论后再切换焦点",
  CONCLUSIONS_HASH_REQUIRED: "规划节点 complete 需要提供 conclusionsHash，请先调用 context_get",
  CONCLUSIONS_HASH_MISMATCH: "conclusionsHash 不匹配，子节点结论可能已变化，请重新 context_get",
  INFO_COLLECTION_REQUIRED: "根节点 start 前必须完成信息收集节点",
  INVALID_CONFIRMATION_TOKEN: "confirmation token 无效或已过期",
  CONFIRMATION_MISMATCH: "confirmation token 对应的节点不匹配",
  REFERENCE_NOT_FOUND: "引用不存在",
  REFERENCE_EXISTS: "引用已存在",
  MEMO_NOT_FOUND: "备忘不存在",
  LOG_APPEND_FAILED: "日志追加失败",
  INVALID_NODE_TYPE: "节点类型无效，必须是 planning 或 execution",
  INVALID_NODE_ROLE: "节点角色无效，派发子节点不能再升级为派发母节点",
  EXECUTION_CANNOT_HAVE_CHILDREN: "执行节点不能创建子节点",
  INVALID_PARENT_STATUS: "父节点状态不允许创建子节点",
  INCOMPLETE_CHILDREN: "存在未完成的子节点",
  CONCURRENT_EXECUTION: "同级节点正在执行中，请遵循一次一个节点原则",
  RULES_HASH_MISMATCH: "规则哈希不匹配，请先获取最新规则",
  INVALID_PARAMS: "参数无效",
  UNKNOWN_PARAMS: "存在未知参数",
  CONTENT_CHANGED: "内容已变更，请重新获取",
  NO_MATCH: "未找到匹配内容",
  MULTI_MATCH: "找到多处匹配，请提供更多上下文",
  GRAPH_CORRUPTED: "节点图数据损坏",
  NODE_DIR_MISSING: "节点目录不存在",
  NODE_INFO_MISSING: "节点 Info.md 不存在",
  GIT_NOT_FOUND: "当前项目不是 git 仓库",
  DISPATCH_CONFLICT: "已有其他工作区正在派发中",
  DISPATCH_NOT_ENABLED: "派发模式未启用",
  DISPATCH_REQUIRED: "派发模式已启用，执行节点必须通过 dispatch_node 派发执行",
  DISPATCH_IN_PROGRESS: "节点正在派发执行中，请等待 subagent 完成",
  INVALID_NODE_STATUS: "节点状态不符合操作要求",
  INVALID_TEST_NODE: "无效的测试节点",
  EXEC_NODE_NOT_FOUND: "关联的执行节点不存在",
  DISPATCH_ALREADY_ENABLED: "派发模式已启用，如需切换模式请先禁用",
  DISPATCH_MODE_CONFLICT: "同一项目只能使用一种派发模式",
  GIT_ENVIRONMENT_LOST: "Git 环境已丢失",
  NODE_NOT_READY: "节点未准备好派发，缺少必要信息",
  DISPATCH_SKIP: "节点无需派发，可直接执行",
  INVALID_DISPATCH_PARENT: "节点不是派发母节点，需先调用 dispatch_node 升级",
  INVALID_DISPATCH_STATUS: "派发状态不正确，需先调用 node_transition(action=start) 开始执行",
  DISPATCH_CHILDREN_EXIST: "派发子节点已存在，无法重复创建",
  INVALID_CONFIG: "配置文件无效",
  VERSION_TOO_HIGH: "数据版本过高，请升级 tanmi-workspace",
  VERSION_READONLY: "数据版本高于当前代码版本，禁止写入",
  UNBOUND_WRITE_DENIED: "安全设置禁止未绑定会话执行写操作",
};
