#!/usr/bin/env npx tsx
/**
 * generate-hook-tools.ts
 *
 * 从工具定义中提取 readonly 信息，生成 Hook 使用的 write-tools.cjs 文件。
 *
 * 逻辑：
 * 1. 扫描 src/tools/*.ts 文件
 * 2. 提取每个工具的 name 和 readonly 属性
 * 3. readonly !== true 的工具加入 WRITE_TOOLS
 * 4. 生成 write-tools.cjs 到 plugin/hooks/generated/
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..");

const TOOLS_DIR = path.join(ROOT_DIR, "src/tools");
const OUTPUT_FILE = path.join(ROOT_DIR, "plugin/hooks/generated/write-tools.cjs");

// 特殊允许的工具（未绑定时也允许执行）
const SPECIAL_ALLOW = [
  "workspace_init",
  "session_bind",
  "session_unbind",
  "config_set",
];

// 流程初始化白名单（phaseSkillInvoked=false 时允许的工具）
// 绑定工作区后必须先调用 Skill 进入流程，此前只允许这些工具
const SKILL_INIT_WHITELIST = [
  // Claude 内置工具
  "Skill",
  "Bash",
  "Read",
  // MCP 工具（简短名）
  // 注：session_unbind 同时在 SPECIAL_ALLOW 中，两个白名单用途不同：
  // - SPECIAL_ALLOW: 未绑定时的写操作特例
  // - SKILL_INIT_WHITELIST: phaseSkillInvoked=false 时的流程强制白名单
  "session_unbind",
  "session_status",
  "tanmi_help",
  "plugin_path",
  // Signal 工具：用于 Skill 流程启动，必须在白名单中
  "signal",
];

// Signal 阶段编码映射（base64 前缀，原编码过长故裁剪）
// 用于 validateSignalPreCheck 解析目标阶段
const SIGNAL_CODES: Record<string, string> = {
  "aW5mbw": "info",    // base64("info") 裁剪
  "VzaWdu": "design",  // base64("sw_design") 裁剪
  "aW1wbA": "impl",    // base64("impl") 裁剪
};

interface ToolInfo {
  name: string;
  readonly: boolean;
  file: string;
}

/**
 * 从 TypeScript 文件中提取工具定义
 *
 * ⚠️ 正则匹配约束（重要）：
 * 1. 工具定义必须在单个 {} 块内完成（不支持跨多行的嵌套对象）
 * 2. `name` 和 `readonly` 属性必须在同一个 {} 块内
 * 3. 工具名称只支持小写字母和下划线 [a-z_]+
 * 4. 变量名必须以 Tool 结尾（如 nodeCreateTool）
 *
 * 如果新增工具不符合以上格式，请同步更新此正则或手动维护 write-tools.cjs
 */
function extractToolsFromFile(filePath: string): ToolInfo[] {
  const content = fs.readFileSync(filePath, "utf-8");
  const fileName = path.basename(filePath);
  const tools: ToolInfo[] = [];

  // 正则匹配约束：
  // - 仅匹配单层 {} 块（[^}]* 不含 } 字符）
  // - name 必须是 "tool_name" 格式（小写+下划线）
  // - readonly 必须是 true 或 false 字面量

  // 按工具定义块分割
  // 查找所有 export const xxxTool = { 或 { name: 开头的块
  const blockPattern = /(?:export\s+const\s+\w+Tool[^=]*=\s*\{|\{\s*name:)[^}]*name:\s*["']([a-z_]+)["'][^}]*\}/g;

  let match;
  while ((match = blockPattern.exec(content)) !== null) {
    const block = match[0];
    const nameMatch = block.match(/name:\s*["']([a-z_]+)["']/);
    const readonlyMatch = block.match(/readonly:\s*(true|false)/);

    if (nameMatch) {
      const name = nameMatch[1];
      // readonly 未定义视为 false（写操作）
      const isReadonly = readonlyMatch ? readonlyMatch[1] === "true" : false;
      tools.push({
        name,
        readonly: isReadonly,
        file: fileName,
      });
    }
  }

  return tools;
}

/**
 * 扫描所有工具文件
 */
function scanToolFiles(): ToolInfo[] {
  const files = fs.readdirSync(TOOLS_DIR)
    .filter(f => f.endsWith(".ts") && f !== "index.ts");

  const allTools: ToolInfo[] = [];

  for (const file of files) {
    const filePath = path.join(TOOLS_DIR, file);
    const tools = extractToolsFromFile(filePath);
    allTools.push(...tools);
  }

  return allTools;
}

/**
 * 生成 write-tools.cjs 文件
 */
function generateWriteTools(tools: ToolInfo[]): void {
  // 筛选写操作工具（readonly !== true）
  const writeTools = tools
    .filter(t => !t.readonly)
    .map(t => t.name)
    .sort();

  // 去重
  const uniqueWriteTools = [...new Set(writeTools)];

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/generate-hook-tools.ts
 * Generated at: ${new Date().toISOString()}
 *
 * 此文件包含 Hook 使用的工具白名单配置，由构建脚本自动生成。
 * 修改工具的 readonly 属性后，运行 npm run generate:hook-tools 重新生成。
 */

module.exports = {
  /**
   * 写操作工具集合
   * 未绑定会话时，这些工具的调用会被 Hook 拒绝（除非在 SPECIAL_ALLOW 中）
   */
  WRITE_TOOLS: new Set([
${uniqueWriteTools.map(t => `    '${t}'`).join(",\n")}
  ]),

  /**
   * 特殊允许工具集合
   * 这些工具即使未绑定会话也允许执行
   */
  SPECIAL_ALLOW: new Set([
${SPECIAL_ALLOW.map(t => `    '${t}'`).join(",\n")}
  ]),

  /**
   * 流程初始化白名单
   * phaseSkillInvoked=false 时允许的工具
   * 绑定工作区后必须先调用 Skill 进入流程，此前只允许这些工具
   */
  SKILL_INIT_WHITELIST: new Set([
${SKILL_INIT_WHITELIST.map(t => `    '${t}'`).join(",\n")}
  ]),

  /**
   * Signal 阶段编码映射（base64 前缀，原编码过长故裁剪）
   * 用于 validateSignalPreCheck 解析目标阶段
   */
  SIGNAL_CODES: {
${Object.entries(SIGNAL_CODES).map(([k, v]) => `    '${k}': '${v}'`).join(",\n")}
  }
};
`;

  // 确保输出目录存在
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");

  // 打印统计信息
  console.log("=== generate-hook-tools ===");
  console.log(`扫描工具文件: ${tools.length} 个工具`);
  console.log(`只读工具: ${tools.filter(t => t.readonly).length} 个`);
  console.log(`写操作工具: ${uniqueWriteTools.length} 个`);
  console.log(`特殊允许: ${SPECIAL_ALLOW.length} 个`);
  console.log(`流程初始化白名单: ${SKILL_INIT_WHITELIST.length} 个`);
  console.log(`Signal 编码: ${Object.keys(SIGNAL_CODES).length} 个`);
  console.log(`输出文件: ${OUTPUT_FILE}`);
  console.log("");
  console.log("写操作工具列表:");
  uniqueWriteTools.forEach(t => console.log(`  - ${t}`));
  console.log("");
  console.log("流程初始化白名单:");
  SKILL_INIT_WHITELIST.forEach(t => console.log(`  - ${t}`));
  console.log("");
  console.log("Signal 编码映射:");
  Object.entries(SIGNAL_CODES).forEach(([k, v]) => console.log(`  - ${k} → ${v}`));
}

// 主流程
function main(): void {
  try {
    const tools = scanToolFiles();
    generateWriteTools(tools);
    console.log("\n生成成功!");
  } catch (error) {
    console.error("生成失败:", error);
    process.exit(1);
  }
}

main();
