#!/usr/bin/env npx tsx
/**
 * generate-hook-tools.ts
 *
 * 从工具定义中提取 readonly 信息，生成 Hook 使用的 write-tools.cjs 文件。
 *
 * 逻辑：
 * 1. 扫描 src/tools/*.ts 文件
 * 2. 提取每个工具的 name 和 readonly 属性
 * 3. readonly !== true 的工具加入 WRITE_TOOLS
 * 4. 生成 write-tools.cjs 到 plugin/hooks/generated/
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..");

const TOOLS_DIR = path.join(ROOT_DIR, "src/tools");
const OUTPUT_FILE = path.join(ROOT_DIR, "plugin/hooks/generated/write-tools.cjs");

// 特殊允许的工具（未绑定时也允许执行）
const SPECIAL_ALLOW = [
  "workspace_init",
  "session_bind",
  "session_unbind",
  "config_set",
];

interface ToolInfo {
  name: string;
  readonly: boolean;
  file: string;
}

/**
 * 从 TypeScript 文件中提取工具定义
 */
function extractToolsFromFile(filePath: string): ToolInfo[] {
  const content = fs.readFileSync(filePath, "utf-8");
  const fileName = path.basename(filePath);
  const tools: ToolInfo[] = [];

  // 匹配工具定义对象
  // 支持两种格式：
  // 1. export const xxxTool: TanmiTool = { name: "xxx", readonly: true/false, ... }
  // 2. { name: "xxx", readonly: true, ... } 在数组中

  // 正则匹配 name 和 readonly 属性
  // 匹配模式: name: "tool_name" ... readonly: true/false
  const toolPattern = /\bname:\s*["']([a-z_]+)["']/g;
  const readonlyPattern = /\breadonly:\s*(true|false)/g;

  // 按工具定义块分割
  // 查找所有 export const xxxTool = { 或 { name: 开头的块
  const blockPattern = /(?:export\s+const\s+\w+Tool[^=]*=\s*\{|\{\s*name:)[^}]*name:\s*["']([a-z_]+)["'][^}]*\}/g;

  let match;
  while ((match = blockPattern.exec(content)) !== null) {
    const block = match[0];
    const nameMatch = block.match(/name:\s*["']([a-z_]+)["']/);
    const readonlyMatch = block.match(/readonly:\s*(true|false)/);

    if (nameMatch) {
      const name = nameMatch[1];
      // readonly 未定义视为 false（写操作）
      const isReadonly = readonlyMatch ? readonlyMatch[1] === "true" : false;
      tools.push({
        name,
        readonly: isReadonly,
        file: fileName,
      });
    }
  }

  return tools;
}

/**
 * 扫描所有工具文件
 */
function scanToolFiles(): ToolInfo[] {
  const files = fs.readdirSync(TOOLS_DIR)
    .filter(f => f.endsWith(".ts") && f !== "index.ts");

  const allTools: ToolInfo[] = [];

  for (const file of files) {
    const filePath = path.join(TOOLS_DIR, file);
    const tools = extractToolsFromFile(filePath);
    allTools.push(...tools);
  }

  return allTools;
}

/**
 * 生成 write-tools.cjs 文件
 */
function generateWriteTools(tools: ToolInfo[]): void {
  // 筛选写操作工具（readonly !== true）
  const writeTools = tools
    .filter(t => !t.readonly)
    .map(t => t.name)
    .sort();

  // 去重
  const uniqueWriteTools = [...new Set(writeTools)];

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/generate-hook-tools.ts
 * Generated at: ${new Date().toISOString()}
 *
 * 此文件包含写操作工具列表，由构建脚本从工具定义中自动提取。
 * 修改工具的 readonly 属性后，运行 npm run generate:hook-tools 重新生成。
 */

module.exports = {
  /**
   * 写操作工具集合
   * 未绑定会话时，这些工具的调用会被 Hook 拒绝（除非在 SPECIAL_ALLOW 中）
   */
  WRITE_TOOLS: new Set([
${uniqueWriteTools.map(t => `    '${t}'`).join(",\n")}
  ]),

  /**
   * 特殊允许工具集合
   * 这些工具即使未绑定会话也允许执行
   */
  SPECIAL_ALLOW: new Set([
${SPECIAL_ALLOW.map(t => `    '${t}'`).join(",\n")}
  ])
};
`;

  // 确保输出目录存在
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");

  // 打印统计信息
  console.log("=== generate-hook-tools ===");
  console.log(`扫描工具文件: ${tools.length} 个工具`);
  console.log(`只读工具: ${tools.filter(t => t.readonly).length} 个`);
  console.log(`写操作工具: ${uniqueWriteTools.length} 个`);
  console.log(`特殊允许: ${SPECIAL_ALLOW.length} 个`);
  console.log(`输出文件: ${OUTPUT_FILE}`);
  console.log("");
  console.log("写操作工具列表:");
  uniqueWriteTools.forEach(t => console.log(`  - ${t}`));
}

// 主流程
function main(): void {
  try {
    const tools = scanToolFiles();
    generateWriteTools(tools);
    console.log("\n生成成功!");
  } catch (error) {
    console.error("生成失败:", error);
    process.exit(1);
  }
}

main();
